#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
set -o xtrace

gcloud compute ssh newplex --zone=us-central1-a --command 'sudo apt-get install git -y'
gcloud compute ssh newplex --zone=us-central1-a --command 'wget -q https://go.dev/dl/go1.25.6.linux-amd64.tar.gz'
gcloud compute ssh newplex --zone=us-central1-a --command 'tar -xzf *.tar.gz'
gcloud compute ssh newplex --zone=us-central1-a --command "echo 'export PATH=\"\$PATH:~/go/bin\"' >> ~/.bashrc"
gcloud compute ssh newplex --zone=us-central1-a --command 'git clone https://github.com/codahale/newplex'
