#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
set -o xtrace

until gcloud compute ssh newplex --zone=us-central1-a --command 'pwd' ; do
  echo "Instance not fully available, retrying in 5 seconds..."
  sleep 5
done
gcloud compute ssh newplex --zone=us-central1-a --command 'sudo apt-get install git -y'
gcloud compute ssh newplex --zone=us-central1-a --command 'wget -q https://go.dev/dl/go1.25.6.linux-amd64.tar.gz'
gcloud compute ssh newplex --zone=us-central1-a --command 'tar -xzf *.tar.gz'
gcloud compute ssh newplex --zone=us-central1-a --command "echo 'export PATH=\"\$PATH:~/go/bin\"' >> ~/.bashrc"
gcloud compute ssh newplex --zone=us-central1-a --command 'git clone https://github.com/codahale/newplex'
gcloud compute ssh newplex --zone=us-central1-a --command 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash'
# shellcheck disable=SC2016
gcloud compute ssh newplex --zone=us-central1-a --command '\. $HOME/.nvm/nvm.sh && nvm install 24'
# shellcheck disable=SC2016
gcloud compute ssh newplex --zone=us-central1-a --command '\. $HOME/.nvm/nvm.sh && npm install -g @google/gemini-cli'